Repository thoth-station/qeb-hwt, pull requests merged in 2020-11, with the labels that each got.

#129 Use neutral conclusion if dependencies are not found
  app.py
Labels: approved, size/XS

#130 Automatic update of dependency thoth-common from 0.20.2 to 0.20.4
  Pipfile.lock
Labels: approved, bot, size/XL

#131 Automatic update of dependency pytest from 6.1.1 to 6.1.2
  Pipfile.lock
Labels: approved, bot, size/XL

#134 Relock Pipfile.lock with package updates
  Pipfile.lock
Labels: size/XL
