Repository thoth-station/qeb-hwt, pull requests merged in 2020-09, with the labels that each got.

#101 Automatic update of dependency thoth-common from 0.16.1 to 0.17.2
  Pipfile.lock
Labels: approved, bot, size/M

#102 remove TODO already solved
  app.py
Labels: approved, size/XS

#103 Automatic update of dependency thoth-common from 0.17.2 to 0.19.0
  Pipfile.lock
Labels: approved, bot, size/L

#104 Automatic update of dependency thoth-report-processing from 0.3.0 to 0.3.4
  Pipfile.lock
Labels: approved, bot

#105 Automatic update of dependency pytest from 6.0.1 to 6.0.2
  Pipfile.lock
Labels: approved, bot, size/L

#107 Automatic update of dependency octomachinery from 0.2.2 to 0.3.0
  Pipfile.lock
Labels: approved, bot, size/L

#108 Automatic update of dependency thoth-common from 0.19.0 to 0.20.0
  Pipfile.lock
Labels: approved, bot, size/L

#111 Add new maintainer
  .thoth.yaml
Labels: approved, size/XS

#114 Release of version 0.3.1
  CHANGELOG.md
  thoth/qeb_hwt/version.py
Labels: approved, bot, size/S
