Repository thoth-station/qeb-hwt, pull requests merged in 2020-04, with the labels that each got.

#34 Setup workflow TTL strategy to reduce preassure causing OOM
  openshift/qeb-hwt-template.yaml
Labels: approved, size/XS

#35 Adjust inputs to read from thoth yaml
  app.py
  workflows/templates/thamos-advise-template.yaml
Labels: approved, size/S

#37 Add shallow clone
  workflows/templates/thamos-advise-template.yaml
Labels: approved, size/XS

#38 removed pre-commit and black, added kebechet managers
  .thoth.yaml
  Pipfile
  Pipfile.lock
Labels: approved, size/XL

#40 Use safe_load to load configuration
  workflows/templates/thamos-advise-template.yaml
Labels: approved, size/XS

#39 Add usage to README file
  README.rst
  docs/INSTALLATION.md
  docs/README.rst
Labels: approved, do-not-merge/work-in-progress, size/M

#41 Little change
  README.rst
Labels: approved, size/XS

#42 handle FileLoadError
  workflows/templates/thamos-advise-template.yaml
Labels: approved, size/XS
