Repository thoth-station/qeb-hwt, pull requests merged in 2020-02, with the labels that each got.

#16 Replaced Pipfile.lock
  Pipfile.lock
Labels: approved, size/L

#6 receive 'workflow finished' webhook
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .pre-commit-config.yaml
  .thoth.yaml
  Pipfile
  Pipfile.lock
  app.py
  docs/Qeb-Hwt + Adviser Workflows.graphml
  docs/Qeb-Hwt + Adviser Workflows.jpg
  docs/README.md
  docs/testWithCurl.md
  fixtures/installation_created.json
  fixtures/integration_installation_created.json
  fixtures/thoth_thamos_advise_finished_1.json
  fixtures/thoth_thamos_advise_finished_1.sha1hmac
  fixtures/thoth_thamos_advise_finished_2.json
  openshift/qeb-hwt-template.yaml
  thoth/qeb_hwt/__init__.py
  thoth/qeb_hwt/version.py
  workflows/templates/thamos-advise-template.yaml
Labels: size/XXL

#24 Thamos exceptions handling
  app.py
  workflows/templates/thamos-advise-template.yaml
Labels: approved, size/L

#22 Tutorial to install Qeb-Hwt App
  README.md
  app.py
  docs/images/DependencyManagementCategory.png
  docs/images/DependencyManagementQebHwt.png
  docs/images/FreeApp.png
  docs/images/GitHubMarketplace.png
  docs/images/InstallApp.png
  docs/images/QebHwyGitHubApp.png
  docs/images/SelectRepos.png
  docs/images/SetupPlan.png
  docs/images/SuccessfullyInstalledApp.png
Labels: approved, size/M

#26 Missing imports, add variable before check.
  app.py
  workflows/templates/thamos-advise-template.yaml
Labels: approved, size/S

#27 Handling VCS use instead of package index from users
  workflows/templates/thamos-advise-template.yaml
Labels: approved, size/S

#28 Logger name
  workflows/templates/thamos-advise-template.yaml
Labels: approved, size/XS

#30 Adjust report error to include errors if they are present
  app.py
Labels: approved, size/S
