Repository thoth-station/qeb-hwt, pull requests merged in 2020-01, with the labels that each got.

#4 Happy New Year!
  app.py
  thoth/qeb_hwt/__init__.py
  thoth/qeb_hwt/version.py
Labels: approved, size/XS

#5 dumping drafts
  docs/new_pr_workflow.md
  docs/workflow-draft-1.jpg
  docs/workflow-draft-2.jpg
Labels: approved, size/XS

#7 Fixed invalid deployment trigger
  openshift/deploymentconfig.yaml
Labels: approved, size/XS

#8 Ultrahook deployment
  openshift/deploymentconfig.yaml
  openshift/ultrahook-template.yaml
Labels: approved, size/M

#9 reorganized stuff to have templates for everything
  .coafile
  docs/newPrWorkflow.md
  openshift/buildConfig-template.yaml
  openshift/buildconfig.yaml
  openshift/configMap-template.yaml
  openshift/deployment-template.yaml
  openshift/deploymentconfig.yaml
  openshift/imageStream-template.yaml
  openshift/imagestream.yaml
  openshift/ultrahook-template.yaml
Labels: size/L

#11 Added thoth_thamos_advise payload fixture
  fixtures/thoth_thamos_advise.json
Labels: approved, size/S

#13 Add draft
  docs/Thamos Advise Argo Workflow.jpg
Labels: approved, do-not-merge/work-in-progress, size/XS
