Repository thoth-station/qeb-hwt, pull requests merged in 2020-07, with the labels that each got.

#64 Moved to report-processing
  OWNERS
  Pipfile
  Pipfile.lock
  app.py
  thoth/qeb_hwt/utils.py
Labels: approved, size/XL

#65 Move utils
  app.py
Labels: approved, size/XS

#66 Remove templates handled by thoth-application
  openshift/buildConfig-template.yaml
  openshift/configMap-template.yaml
  openshift/deployment-template.yaml
  openshift/imageStream-template.yaml
  openshift/qeb-hwt-template.yaml
  openshift/service.yaml
Labels: approved, size/L

#68 Using Python 3.8
  Pipfile
  Pipfile.lock
Labels: approved, size/L

#73 Automatic update of dependency pytest from 5.4.3 to 6.0.0rc1
  Pipfile.lock
Labels: approved, bot, size/L

#72 Automatic update of dependency pandas from 1.0.5 to 1.1.0rc0
  Pipfile.lock
Labels: approved, bot, size/L

#71 Automatic update of dependency thoth-common from 0.14.1 to 0.14.2
  Pipfile.lock
Labels: approved, bot, size/L

#74 Automatic update of dependency thoth-common from 0.14.1 to 0.14.2
  Pipfile.lock
Labels: approved, bot, size/M

#69 include aicoe-ci configuration file
  .aicoe-ci.yaml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
Labels: approved, size/M

#75 Adjust imports
  Pipfile
  Pipfile.lock
  app.py
Labels: approved, size/M
