Repository thoth-station/qeb-hwt, pull requests merged in 2022-03, with the labels that each got.

#158 Update pyproject.toml to use Python 3.8
  pyproject.toml
Labels: size/XS, lifecycle/stale

#163 updating pre-commit protocol
  .pre-commit-config.yaml
Labels: size/S

#164 Automatic update of base-image in CI
  .aicoe-ci.yaml
Labels: size/XS, approved, ok-to-test
